pipeline {
    agent any

    stages {
        stage('Git clone') {
            steps {
                    sh 'mkdir test2'
                    git branch: 'frontend-dev', url: 'https://github.com/beyond-sw-camp/be06-4th-SimKids.git'
            }
        }
    }
}